//! Lane — one isolated execution unit: a detached thread, a mailbox,
//! and the engine state it exclusively owns.
//!
//! This file is part of the pdf_manipulator host layer (NOT upstream).
//!
//! A lane is the native twin of a Web Worker. It is decision-free:
//! routing, pinning, queuing, and scheduling all live in the shared
//! Dart Router. The lane body does exactly one thing — pull jobs from
//! its mailbox and run them against its own `LaneState` through the
//! shared `handle_request` brain.
//!
//! ## Ownership (the race-freedom contract)
//!
//! - `LaneState` is created ON the lane thread and dropped when the
//!   thread exits. No other code can ever reference it — teardown is
//!   a plain Rust drop, never a cross-thread free.
//! - The only cross-thread surfaces are small and single-purpose:
//!   the mailbox sender, the lane cancel flag, the job-ticket map,
//!   and the I/O channel registry. Each is documented at its site.
//!
//! ## Kill protocol (why no notify callback ever fires after a kill)
//!
//! Killers (lane kill / job cancel) wake parked I/O by taking each
//! channel's SyncPair mutex, setting FLAG_CANCELLED, and notifying.
//! Readers/writers hold that same mutex from request-write through
//! their notify call into the condvar wait. Therefore a kill can only
//! land while the lane thread is parked (or absent) — never between
//! its token re-check and its notify call. Once the kill returns, the
//! lane thread will never invoke a Dart notify callback again, so the
//! caller may close NativeCallables immediately.

use crate::host::bridge_api::{handle_request, BoxedReader, BoxedWriter};
use crate::host::binary_codec::ResponseWriter;
use crate::host::lane_state::LaneState;
use crate::host::native::callback_reader::CallbackReader;
use crate::host::native::callback_writer::CallbackWriter;
use crate::host::native::cancel::CancelToken;
use crate::host::native::shared_buffer::{self as sb, read_channel as rc, write_channel as wc};
use crossbeam_channel::Receiver;
use std::collections::HashMap;
use std::panic::{catch_unwind, AssertUnwindSafe};
use std::sync::atomic::{AtomicBool, Ordering};
use std::sync::{Arc, Mutex};

// ── Job — one operation, routed to exactly one lane ────────────────

/// A source channel descriptor: shared buffer + Dart notify callback.
pub struct SourceChannel {
    /// Address of the read-channel shared buffer (Dart-allocated).
    pub buf: usize,
    /// Dart NativeCallable listener pointer; None for absent slots.
    pub notify: Option<unsafe extern "C" fn()>,
    /// Source length in bytes.
    pub length: i64,
    /// Keep this channel registered after the job ends. Set for
    /// sources that a handle-creating op (open/edit) moves into the
    /// document — the channel then lives until the handle is released
    /// and must stay reachable by kill/cancel wakes.
    pub keep: bool,
}

/// A sink channel descriptor: shared buffer + Dart notify callback.
pub struct SinkChannel {
    /// Address of the write-channel shared buffer (Dart-allocated).
    pub buf: usize,
    /// Dart NativeCallable listener pointer; None for absent slots.
    pub notify: Option<unsafe extern "C" fn()>,
}

/// One operation. Built by `lane_submit` from FFI arguments, consumed
/// once by the lane thread.
pub struct Job {
    /// Job identity, generated by the Dart Router (single-threaded —
    /// the one owner of job identity).
    pub job_id: u64,
    /// Binary-encoded request (op name + args).
    pub request: Vec<u8>,
    /// Indexed source channels.
    pub sources: Vec<SourceChannel>,
    /// Indexed sink channels.
    pub sinks: Vec<SinkChannel>,
    /// allo-isolate port for the result bytes.
    pub result_port: i64,
    /// This job's cancel flag (also held in the controller's ticket
    /// map so `lane_job_cancel` can reach it).
    pub cancel: Arc<AtomicBool>,
}

// ── ChannelRegistry — live I/O buffers, woken on cancellation ──────

#[derive(Clone, Copy)]
enum ChannelKind {
    Read,
    Write,
}

/// Registry owner tag for held channels (alive for a handle's
/// lifetime, not currently adopted by any job). Real job ids come
/// from the Dart Router's counter and start at 1.
const HELD_OWNER: u64 = u64::MAX;

/// Registry of the I/O channels currently parked-or-parkable on this
/// lane. The lane thread registers a job's channels before building
/// readers/writers and unregisters them before posting the result —
/// so an address in here always points at live, Dart-owned memory
/// (Dart frees a job's buffers only after receiving its result).
///
/// Lock order: registry lock → channel pair mutex. The lane thread
/// never takes the registry lock while holding a pair mutex, so this
/// order cannot deadlock.
pub struct ChannelRegistry {
    entries: Mutex<HashMap<usize, (ChannelKind, u64)>>,
}

impl ChannelRegistry {
    /// Create an empty registry.
    pub fn new() -> Self {
        Self { entries: Mutex::new(HashMap::new()) }
    }

    /// Register a job's channels AND adopt every held channel on
    /// this lane under the job's id. Adoption is what makes per-job
    /// cancel instant even when the op parks inside a handle's held
    /// reader (created by an earlier job): lanes run one job at a
    /// time, so any channel parked during this job belongs to it.
    fn register(&self, job: &Job) {
        let mut entries = self.entries.lock().unwrap();
        for (_, owner) in entries.values_mut() {
            if *owner == HELD_OWNER {
                *owner = job.job_id;
            }
        }
        for s in &job.sources {
            if s.buf != 0 {
                entries.insert(s.buf, (ChannelKind::Read, job.job_id));
            }
        }
        for s in &job.sinks {
            if s.buf != 0 {
                entries.insert(s.buf, (ChannelKind::Write, job.job_id));
            }
        }
    }

    /// Undo `register` at job end: kept sources and adopted held
    /// channels park back under HELD_OWNER; everything else leaves
    /// the registry (Dart frees those buffers after the result).
    fn release_job(&self, job: &Job) {
        let mut entries = self.entries.lock().unwrap();
        for s in &job.sources {
            if !s.keep {
                entries.remove(&s.buf);
            }
        }
        for s in &job.sinks {
            entries.remove(&s.buf);
        }
        for (_, owner) in entries.values_mut() {
            if *owner == job.job_id {
                *owner = HELD_OWNER;
            }
        }
    }

    /// Remove one held channel (handle released). The caller frees
    /// the buffer only after this returns — never while registered.
    pub fn release_one(&self, buf: usize) {
        self.entries.lock().unwrap().remove(&buf);
    }

    /// Wake every registered channel with FLAG_CANCELLED (lane kill).
    pub fn cancel_all(&self) {
        let entries = self.entries.lock().unwrap();
        for (&buf, &(kind, _)) in entries.iter() {
            unsafe { cancel_channel(buf as *mut u8, kind) };
        }
    }

    /// Wake one job's registered channels with FLAG_CANCELLED.
    pub fn cancel_job(&self, job_id: u64) {
        let entries = self.entries.lock().unwrap();
        for (&buf, &(kind, owner)) in entries.iter() {
            if owner == job_id {
                unsafe { cancel_channel(buf as *mut u8, kind) };
            }
        }
    }

    /// Number of currently registered channels. Diagnostics and tests
    /// only — never used for decisions.
    pub fn live_count(&self) -> usize {
        self.entries.lock().unwrap().len()
    }
}

impl Default for ChannelRegistry {
    fn default() -> Self {
        Self::new()
    }
}

/// Set FLAG_CANCELLED and signal one channel, holding its pair mutex
/// throughout — the lock-ordering guarantee the kill protocol rests on.
///
/// # Safety
/// `buf` must be a live channel buffer initialized via `sb::init_sync`.
unsafe fn cancel_channel(buf: *mut u8, kind: ChannelKind) {
    let (sync_offset, flags_offset) = match kind {
        ChannelKind::Read => (rc::OFFSET_SYNC_PTR, rc::OFFSET_FLAGS),
        ChannelKind::Write => (wc::OFFSET_SYNC_PTR, wc::OFFSET_FLAGS),
    };
    let pair = sb::get_sync(buf, sync_offset);
    let _guard = pair.mutex.lock().unwrap();
    sb::set_flag_bits(buf, flags_offset, sb::FLAG_CANCELLED);
    pair.condvar.notify_all();
}

// ── LaneController — the cross-thread control surface ──────────────

/// Everything a killer/submitter may touch from outside the lane
/// thread. Held in the global lane table behind an Arc; the lane
/// thread holds its own clone so the controller outlives a racing
/// table removal.
pub struct LaneController {
    /// Job intake. `None` after kill — the lane thread drains the
    /// channel and exits when the sender is gone.
    pub(crate) mailbox: Mutex<Option<crossbeam_channel::Sender<Job>>>,
    /// Lane-wide kill flag. Set once by `lane_kill`, never cleared.
    pub cancel: Arc<AtomicBool>,
    /// Live I/O channels for wake-on-cancel.
    pub channels: ChannelRegistry,
    /// job_id → job cancel flag, for `lane_job_cancel`. Inserted at
    /// submit (before enqueue, so a cancel can always find its job),
    /// removed by the lane thread when the job finishes.
    pub(crate) tickets: Mutex<HashMap<u64, Arc<AtomicBool>>>,
}

// ── The lane body ───────────────────────────────────────────────────

/// The lane thread's main loop. Creates the lane's state, drains the
/// mailbox, exits when the sender is dropped (kill or shutdown).
///
/// Budget-slot release is NOT done here — the lane table wraps this
/// call in an RAII guard at the spawn site, so the slot is returned
/// even if this thread unwinds.
pub fn lane_main(mailbox: Receiver<Job>, controller: Arc<LaneController>) {
    let mut state = LaneState::new();

    while let Ok(job) = mailbox.recv() {
        run_job(&mut state, &controller, job);
    }

    // Mailbox closed: the lane is dead. `state` drops here, freeing
    // every handle this lane owned — on this thread, the only thread
    // that ever touched it.
}

/// Execute one job against the lane's state and post the result.
fn run_job(state: &mut LaneState, controller: &LaneController, job: Job) {
    // Dequeued after a kill or a per-job cancel: the notify callbacks
    // may be dead and the buffers may be gone. Touch neither. The
    // Dart Router already resolved this job's task as cancelled (it
    // owns completion after kill); this post is a harmless no-op if
    // the port is closed.
    if controller.cancel.load(Ordering::SeqCst) || job.cancel.load(Ordering::SeqCst) {
        post_result(job.result_port, ResponseWriter::cancelled());
        controller.tickets.lock().unwrap().remove(&job.job_id);
        return;
    }

    // Register channels BEFORE constructing readers/writers. The
    // registry mutex orders this against cancel_all/cancel_job: a
    // registration that lands after a cancel is guaranteed to see the
    // cancel flag at the reader's first I/O check.
    controller.channels.register(&job);

    let token = CancelToken::new(controller.cancel.clone(), job.cancel.clone());

    // Engine ops return Result for every expected failure; a panic
    // here is a bug in the engine. Catching it keeps the lane (and
    // every other handle on it) alive, at the cost of this one job.
    let result = catch_unwind(AssertUnwindSafe(|| {
        let mut sources = Vec::with_capacity(job.sources.len());
        for s in &job.sources {
            if s.buf != 0 && s.notify.is_some() && s.length > 0 {
                let reader = unsafe {
                    CallbackReader::new(
                        s.buf as *mut u8,
                        s.notify.unwrap(),
                        s.length as u64,
                        token.clone(),
                    )
                };
                sources.push(BoxedReader(Box::new(reader)));
            }
        }

        let mut sinks = Vec::with_capacity(job.sinks.len());
        for s in &job.sinks {
            if s.buf != 0 && s.notify.is_some() {
                let writer = unsafe {
                    CallbackWriter::new(s.buf as *mut u8, s.notify.unwrap(), token.clone())
                };
                sinks.push(BoxedWriter(Box::new(writer)));
            }
        }

        handle_request(state, &job.request, None, sources, sinks)
    }));

    // Release BEFORE posting: the post triggers Dart's buffer free
    // for non-kept channels, which must never race a canceller
    // walking the registry. Kept + adopted channels return to HELD.
    controller.channels.release_job(&job);
    controller.tickets.lock().unwrap().remove(&job.job_id);

    // A cancel that landed mid-op makes the engine unwind with an
    // I/O error — but the caller must see the typed cancelled status,
    // identical to a pre-dequeue cancel. The flags are set-once, so
    // this check cannot misfire on a job that finished normally.
    let was_cancelled = controller.cancel.load(Ordering::SeqCst)
        || job.cancel.load(Ordering::SeqCst);

    let bytes = if was_cancelled {
        ResponseWriter::cancelled()
    } else {
        match result {
            Ok(bytes) => bytes,
            Err(_) => ResponseWriter::error("internal error: engine operation panicked"),
        }
    };
    post_result(job.result_port, bytes);
}

/// Post result bytes to the job's Dart port. A closed port (job
/// cancelled, instance disposed) makes this a safe no-op.
pub(crate) fn post_result(port: i64, bytes: Vec<u8>) {
    let isolate = allo_isolate::Isolate::new(port);
    isolate.post(allo_isolate::ZeroCopyBuffer(bytes));
}

#[cfg(test)]
mod tests {
    use super::*;

    unsafe extern "C" fn noop_notify() {}

    fn read_buf() -> Vec<u8> {
        let mut buf = vec![0u8; rc::TOTAL_SIZE];
        unsafe { sb::init_sync(buf.as_mut_ptr(), rc::OFFSET_SYNC_PTR) };
        buf
    }

    fn job_with_source(job_id: u64, buf: &mut [u8], keep: bool) -> Job {
        Job {
            job_id,
            request: vec![],
            sources: vec![SourceChannel {
                buf: buf.as_mut_ptr() as usize,
                notify: Some(noop_notify),
                length: 1024,
                keep,
            }],
            sinks: vec![],
            result_port: 0,
            cancel: Arc::new(AtomicBool::new(false)),
        }
    }

    #[test]
    fn kept_channel_survives_job_and_is_adopted_by_the_next() {
        let registry = ChannelRegistry::new();
        let mut buf = read_buf();

        // Job 1 keeps its source: after release it parks under HELD.
        let job1 = job_with_source(1, &mut buf, true);
        registry.register(&job1);
        registry.release_job(&job1);
        assert_eq!(registry.live_count(), 1);

        // A cancel for a FINISHED job must not touch the held channel.
        registry.cancel_job(1);
        assert!(!sb::has_flag(buf.as_ptr(), rc::OFFSET_FLAGS, sb::FLAG_CANCELLED));

        // Job 2 (no channels of its own) adopts the held channel —
        // cancelling job 2 now wakes the held reader it may be
        // parked in. This is the held-reader cancellation guarantee.
        let job2 = Job {
            job_id: 2,
            request: vec![],
            sources: vec![],
            sinks: vec![],
            result_port: 0,
            cancel: Arc::new(AtomicBool::new(false)),
        };
        registry.register(&job2);
        registry.cancel_job(2);
        assert!(sb::has_flag(buf.as_ptr(), rc::OFFSET_FLAGS, sb::FLAG_CANCELLED));

        // After job 2 the channel parks back under HELD...
        registry.release_job(&job2);
        assert_eq!(registry.live_count(), 1);

        // ...until the handle is released — then it leaves for good.
        registry.release_one(buf.as_ptr() as usize);
        assert_eq!(registry.live_count(), 0);

        unsafe { sb::destroy_sync(buf.as_mut_ptr(), rc::OFFSET_SYNC_PTR) };
    }

    #[test]
    fn non_kept_channels_leave_the_registry_at_job_end() {
        let registry = ChannelRegistry::new();
        let mut buf = read_buf();

        let job = job_with_source(5, &mut buf, false);
        registry.register(&job);
        assert_eq!(registry.live_count(), 1);
        registry.release_job(&job);
        assert_eq!(registry.live_count(), 0);

        unsafe { sb::destroy_sync(buf.as_mut_ptr(), rc::OFFSET_SYNC_PTR) };
    }
}
